/*
 * Copyright 2016 Warkdev.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package eu.jangos.manager.gui.frame;

import eu.jangos.manager.gui.selection.tree.CheckTreeManager;
import javax.swing.JTree;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import javax.swing.tree.MutableTreeNode;

/**
 * FrameManageRoles is the frame handling all commands assignment to roles.
 * @author Warkdev
 * @version 1.0
 * @since 17-02-2016
 */
public class FrameManageRoles extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrameManageRoles
     */
    public FrameManageRoles() {
        initComponents();
        
        DefaultMutableTreeNode rootNode = new DefaultMutableTreeNode("All");    
        
        DefaultMutableTreeNode  child = new DefaultMutableTreeNode("Realm");
        child.add(new DefaultMutableTreeNode("login"));
        child.add(new DefaultMutableTreeNode("test"));
        child.add(new DefaultMutableTreeNode("test2"));
        child.add(new DefaultMutableTreeNode("test3"));
        child.add(new DefaultMutableTreeNode("test5"));
        rootNode.add(child);
        
        DefaultMutableTreeNode child2 = new DefaultMutableTreeNode("Parameters");
        child2.add(new DefaultMutableTreeNode("create"));
        child2.add(new DefaultMutableTreeNode("delete"));
        child2.add(new DefaultMutableTreeNode("update"));
        child2.add(new DefaultMutableTreeNode("test3"));
        child2.add(new DefaultMutableTreeNode("test5"));
        rootNode.add(child2);
        DefaultTreeModel treeModel = new DefaultTreeModel(rootNode);
        
        this.jTreeCommands.setModel(treeModel);
        //this.jTreeCommands = new JTree(treeModel);
        
        checkTreeManager = new CheckTreeManager(this.jTreeCommands);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPaneCommands = new javax.swing.JScrollPane();
        jTreeCommands = new javax.swing.JTree();

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("eu/jangos/manager/Bundle"); // NOI18N
        setTitle(bundle.getString("FrameManageRoles.title")); // NOI18N

        jTreeCommands.setShowsRootHandles(true);
        jScrollPaneCommands.setViewportView(jTreeCommands);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(247, Short.MAX_VALUE)
                .addComponent(jScrollPaneCommands, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPaneCommands, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPaneCommands;
    private javax.swing.JTree jTreeCommands;
    // End of variables declaration//GEN-END:variables
    private CheckTreeManager checkTreeManager;
}
