/*
 * Copyright 2016 Warkdev.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package eu.jangos.manager.gui.frame;

import eu.jangos.manager.controller.LocaleService;
import eu.jangos.manager.controller.ParameterService;
import eu.jangos.manager.controller.RolesService;
import eu.jangos.manager.model.Locale;
import eu.jangos.manager.model.Parameter1;
import eu.jangos.manager.model.Roles;
import eu.jangos.manager.utils.ParameterConstants;
import eu.jangos.manager.utils.Utils;
import javax.swing.DefaultComboBoxModel;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * FrameAuthenticationParameters is the frame used to manage the parameters of the authentication server.
 * @author Warkdev
 * @version 1.0
 * @since 14-02-2016
 */
public class FrameAuthenticationParameters extends javax.swing.JInternalFrame {

    private static final Logger logger = LoggerFactory.getLogger(FrameManageAccount.class);
    private static final String ICON_IMAGE = "/images/parameters.png";
    
    private final ParameterService ps;
    private final LocaleService ls;
    private final RolesService rs;
    
    /**
     * Creates new form FrameAuthenticationParameters
     */
    public FrameAuthenticationParameters() {
        initComponents();
        
        this.ps = null;
        this.ls = null;
        this.rs = null;
        
        this.setFrameIcon(Utils.createImageIcon(ICON_IMAGE, getClass()));                
    }

    public FrameAuthenticationParameters(ParameterService ps, LocaleService ls, RolesService rs) {
        initComponents();                                        
        
        this.ps = ps;
        this.ls = ls;
        this.rs = rs;
        
        this.setFrameIcon(Utils.createImageIcon(ICON_IMAGE, getClass()));
        
        this.jTFAddress.setText(this.ps.getParameter(ParameterConstants.KEY_AUTH_ADDRESS));
        this.jSpinnerPort.setValue(Integer.parseInt(this.ps.getParameter(ParameterConstants.KEY_AUTH_PORT)));
        this.jTFVersion.setText(this.ps.getParameter(ParameterConstants.KEY_AUTH_VERSION));
        this.jSpinnerTimeout.setValue(Integer.parseInt(this.ps.getParameter(ParameterConstants.KEY_AUTH_TIMEOUT)));
        this.jCBLocale.setModel(new DefaultComboBoxModel(this.ls.getAllLocale().toArray()));
        this.jCBLocale.setSelectedItem(this.ls.getLocaleForString(this.ps.getParameter(ParameterConstants.KEY_DEFAULT_LOCALE)));   
        this.jSpinnerMinBuild.setValue(this.ps.getParameter(ParameterConstants.KEY_MIN_SUPPORTED_BUILD));
        this.jSpinnerMaxBuild.setValue(this.ps.getParameter(ParameterConstants.KEY_MAX_SUPPORTED_BUILD));
        this.jSpinnerFailedAttempt.setValue(Integer.parseInt(this.ps.getParameter(ParameterConstants.KEY_MAX_FAILED_ATTEMPT)));
        this.jCBRoles.setModel(new DefaultComboBoxModel(this.rs.getAllRoles().toArray()));
        this.jCBRoles.setSelectedItem(this.rs.getRole(this.ps.getParameter(ParameterConstants.KEY_DEFAULT_ROLE)));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanelServerControls = new javax.swing.JPanel();
        jButtonSave = new javax.swing.JButton();
        jTabbedPane = new javax.swing.JTabbedPane();
        jPanelServer = new javax.swing.JPanel();
        jPanelServerParams = new javax.swing.JPanel();
        jLabelPort = new javax.swing.JLabel();
        jSpinnerPort = new javax.swing.JSpinner();
        jLabelAddress = new javax.swing.JLabel();
        jTFAddress = new javax.swing.JTextField();
        jLabelVersion = new javax.swing.JLabel();
        jTFVersion = new javax.swing.JTextField();
        jLabelTimeout = new javax.swing.JLabel();
        jSpinnerTimeout = new javax.swing.JSpinner();
        jPanelLogin = new javax.swing.JPanel();
        jPanelLoginParams = new javax.swing.JPanel();
        jLabelLocale = new javax.swing.JLabel();
        jCBLocale = new javax.swing.JComboBox();
        jLabelMaxFailedAttempt = new javax.swing.JLabel();
        jSpinnerFailedAttempt = new javax.swing.JSpinner();
        jLabelMinBuild = new javax.swing.JLabel();
        jLabelMaxBuild = new javax.swing.JLabel();
        jSpinnerMaxBuild = new javax.swing.JSpinner();
        jSpinnerMinBuild = new javax.swing.JSpinner();
        jLabelRole = new javax.swing.JLabel();
        jCBRoles = new javax.swing.JComboBox();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("eu/jangos/manager/Bundle"); // NOI18N
        setTitle(bundle.getString("FrameAuthenticationParameters.title")); // NOI18N
        setMaximumSize(new java.awt.Dimension(333, 253));
        setMinimumSize(new java.awt.Dimension(333, 253));
        setPreferredSize(new java.awt.Dimension(333, 253));

        jButtonSave.setText(bundle.getString("FrameAuthenticationParameters.jButtonSave.text")); // NOI18N
        jButtonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveActionPerformed(evt);
            }
        });
        jPanelServerControls.add(jButtonSave);

        getContentPane().add(jPanelServerControls, java.awt.BorderLayout.PAGE_END);

        jTabbedPane.setMaximumSize(new java.awt.Dimension(60, 40));
        jTabbedPane.setMinimumSize(new java.awt.Dimension(60, 40));
        jTabbedPane.setPreferredSize(new java.awt.Dimension(60, 40));

        jPanelServer.setMaximumSize(new java.awt.Dimension(60, 60));
        jPanelServer.setMinimumSize(new java.awt.Dimension(60, 60));
        jPanelServer.setPreferredSize(new java.awt.Dimension(60, 60));
        jPanelServer.setLayout(new java.awt.BorderLayout());

        jPanelServerParams.setLayout(new java.awt.GridBagLayout());

        jLabelPort.setText(bundle.getString("FrameAuthenticationParameters.jLabelPort.text")); // NOI18N
        jLabelPort.setMaximumSize(new java.awt.Dimension(110, 25));
        jLabelPort.setMinimumSize(new java.awt.Dimension(110, 25));
        jLabelPort.setPreferredSize(new java.awt.Dimension(110, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        jPanelServerParams.add(jLabelPort, gridBagConstraints);

        jSpinnerPort.setModel(new javax.swing.SpinnerNumberModel(1, 1, 65535, 1));
        jSpinnerPort.setMaximumSize(new java.awt.Dimension(110, 25));
        jSpinnerPort.setMinimumSize(new java.awt.Dimension(110, 25));
        jSpinnerPort.setPreferredSize(new java.awt.Dimension(110, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        jPanelServerParams.add(jSpinnerPort, gridBagConstraints);

        jLabelAddress.setText(bundle.getString("FrameAuthenticationParameters.jLabelAddress.text")); // NOI18N
        jLabelAddress.setMaximumSize(new java.awt.Dimension(110, 25));
        jLabelAddress.setMinimumSize(new java.awt.Dimension(110, 25));
        jLabelAddress.setPreferredSize(new java.awt.Dimension(110, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        jPanelServerParams.add(jLabelAddress, gridBagConstraints);

        jTFAddress.setMaximumSize(new java.awt.Dimension(110, 25));
        jTFAddress.setMinimumSize(new java.awt.Dimension(110, 25));
        jTFAddress.setPreferredSize(new java.awt.Dimension(110, 25));
        jPanelServerParams.add(jTFAddress, new java.awt.GridBagConstraints());

        jLabelVersion.setText(bundle.getString("FrameAuthenticationParameters.jLabelVersion.text")); // NOI18N
        jLabelVersion.setMaximumSize(new java.awt.Dimension(110, 25));
        jLabelVersion.setMinimumSize(new java.awt.Dimension(110, 25));
        jLabelVersion.setPreferredSize(new java.awt.Dimension(110, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        jPanelServerParams.add(jLabelVersion, gridBagConstraints);

        jTFVersion.setMaximumSize(new java.awt.Dimension(110, 25));
        jTFVersion.setMinimumSize(new java.awt.Dimension(110, 25));
        jTFVersion.setPreferredSize(new java.awt.Dimension(110, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        jPanelServerParams.add(jTFVersion, gridBagConstraints);

        jLabelTimeout.setText(bundle.getString("FrameAuthenticationParameters.jLabelTimeout.text")); // NOI18N
        jLabelTimeout.setMaximumSize(new java.awt.Dimension(110, 25));
        jLabelTimeout.setMinimumSize(new java.awt.Dimension(110, 25));
        jLabelTimeout.setPreferredSize(new java.awt.Dimension(110, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 4;
        jPanelServerParams.add(jLabelTimeout, gridBagConstraints);

        jSpinnerTimeout.setModel(new javax.swing.SpinnerNumberModel(30, 1, 120, 1));
        jSpinnerTimeout.setMaximumSize(new java.awt.Dimension(110, 25));
        jSpinnerTimeout.setMinimumSize(new java.awt.Dimension(110, 25));
        jSpinnerTimeout.setPreferredSize(new java.awt.Dimension(110, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 4;
        jPanelServerParams.add(jSpinnerTimeout, gridBagConstraints);

        jPanelServer.add(jPanelServerParams, java.awt.BorderLayout.CENTER);

        jTabbedPane.addTab(bundle.getString("FrameAuthenticationParameters.jPanelServer.TabConstraints.tabTitle"), jPanelServer); // NOI18N

        jPanelLogin.setLayout(new java.awt.BorderLayout());

        jPanelLoginParams.setLayout(new java.awt.GridBagLayout());

        jLabelLocale.setText(bundle.getString("FrameAuthenticationParameters.jLabelLocale.text")); // NOI18N
        jLabelLocale.setMaximumSize(new java.awt.Dimension(110, 25));
        jLabelLocale.setMinimumSize(new java.awt.Dimension(110, 25));
        jLabelLocale.setPreferredSize(new java.awt.Dimension(110, 25));
        jPanelLoginParams.add(jLabelLocale, new java.awt.GridBagConstraints());

        jCBLocale.setMaximumSize(new java.awt.Dimension(110, 25));
        jCBLocale.setMinimumSize(new java.awt.Dimension(110, 25));
        jCBLocale.setPreferredSize(new java.awt.Dimension(110, 25));
        jPanelLoginParams.add(jCBLocale, new java.awt.GridBagConstraints());

        jLabelMaxFailedAttempt.setText(bundle.getString("FrameAuthenticationParameters.jLabelMaxFailedAttempt.text")); // NOI18N
        jLabelMaxFailedAttempt.setMaximumSize(new java.awt.Dimension(110, 25));
        jLabelMaxFailedAttempt.setMinimumSize(new java.awt.Dimension(110, 25));
        jLabelMaxFailedAttempt.setPreferredSize(new java.awt.Dimension(110, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        jPanelLoginParams.add(jLabelMaxFailedAttempt, gridBagConstraints);

        jSpinnerFailedAttempt.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1)));
        jSpinnerFailedAttempt.setMaximumSize(new java.awt.Dimension(110, 25));
        jSpinnerFailedAttempt.setMinimumSize(new java.awt.Dimension(110, 25));
        jSpinnerFailedAttempt.setPreferredSize(new java.awt.Dimension(110, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        jPanelLoginParams.add(jSpinnerFailedAttempt, gridBagConstraints);

        jLabelMinBuild.setText(bundle.getString("FrameAuthenticationParameters.jLabelMinBuild.text")); // NOI18N
        jLabelMinBuild.setMaximumSize(new java.awt.Dimension(110, 25));
        jLabelMinBuild.setMinimumSize(new java.awt.Dimension(110, 25));
        jLabelMinBuild.setPreferredSize(new java.awt.Dimension(110, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 2;
        jPanelLoginParams.add(jLabelMinBuild, gridBagConstraints);

        jLabelMaxBuild.setText(bundle.getString("FrameAuthenticationParameters.jLabelMaxBuild.text")); // NOI18N
        jLabelMaxBuild.setMaximumSize(new java.awt.Dimension(110, 25));
        jLabelMaxBuild.setMinimumSize(new java.awt.Dimension(110, 25));
        jLabelMaxBuild.setPreferredSize(new java.awt.Dimension(110, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 3;
        jPanelLoginParams.add(jLabelMaxBuild, gridBagConstraints);

        jSpinnerMaxBuild.setModel(new javax.swing.SpinnerListModel(new String[] {"5875", "6005", "6141"}));
        jSpinnerMaxBuild.setMaximumSize(new java.awt.Dimension(110, 25));
        jSpinnerMaxBuild.setMinimumSize(new java.awt.Dimension(110, 25));
        jSpinnerMaxBuild.setPreferredSize(new java.awt.Dimension(110, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 3;
        jPanelLoginParams.add(jSpinnerMaxBuild, gridBagConstraints);

        jSpinnerMinBuild.setModel(new javax.swing.SpinnerListModel(new String[] {"5875", "6005", "6141"}));
        jSpinnerMinBuild.setMaximumSize(new java.awt.Dimension(110, 25));
        jSpinnerMinBuild.setMinimumSize(new java.awt.Dimension(110, 25));
        jSpinnerMinBuild.setPreferredSize(new java.awt.Dimension(110, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 2;
        jPanelLoginParams.add(jSpinnerMinBuild, gridBagConstraints);

        jLabelRole.setText(bundle.getString("FrameAuthenticationParameters.jLabelRole.text")); // NOI18N
        jLabelRole.setMaximumSize(new java.awt.Dimension(110, 25));
        jLabelRole.setMinimumSize(new java.awt.Dimension(110, 25));
        jLabelRole.setPreferredSize(new java.awt.Dimension(110, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        jPanelLoginParams.add(jLabelRole, gridBagConstraints);

        jCBRoles.setMaximumSize(new java.awt.Dimension(110, 25));
        jCBRoles.setMinimumSize(new java.awt.Dimension(110, 25));
        jCBRoles.setPreferredSize(new java.awt.Dimension(110, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        jPanelLoginParams.add(jCBRoles, gridBagConstraints);

        jPanelLogin.add(jPanelLoginParams, java.awt.BorderLayout.CENTER);

        jTabbedPane.addTab(bundle.getString("FrameAuthenticationParameters.jPanelLogin.TabConstraints.tabTitle"), jPanelLogin); // NOI18N

        getContentPane().add(jTabbedPane, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveActionPerformed
        saveParam(ParameterConstants.KEY_AUTH_PORT, ""+this.jSpinnerPort.getValue());
        saveParam(ParameterConstants.KEY_AUTH_ADDRESS, this.jTFAddress.getText());
        saveParam(ParameterConstants.KEY_AUTH_TIMEOUT, ""+this.jSpinnerTimeout.getValue());
        saveParam(ParameterConstants.KEY_AUTH_VERSION, this.jTFVersion.getText());       
        saveParam(ParameterConstants.KEY_DEFAULT_LOCALE, ((Locale) this.jCBLocale.getSelectedItem()).getLocaleString());
        saveParam(ParameterConstants.KEY_MAX_FAILED_ATTEMPT, ""+this.jSpinnerFailedAttempt.getValue());
        saveParam(ParameterConstants.KEY_MIN_SUPPORTED_BUILD, ""+this.jSpinnerMinBuild.getValue());
        saveParam(ParameterConstants.KEY_MAX_SUPPORTED_BUILD, ""+this.jSpinnerMaxBuild.getValue());
        saveParam(ParameterConstants.KEY_DEFAULT_ROLE, ((Roles) this.jCBRoles.getSelectedItem()).getName());
    }//GEN-LAST:event_jButtonSaveActionPerformed

    private void saveParam(String key, String value)
    {
        Parameter1 p = this.ps.getParameterObject(key);
        
        if(p != null && !p.getVal().equals(value))
        {
            p.setVal(value);
            this.ps.save(p);
        }                
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSave;
    private javax.swing.JComboBox jCBLocale;
    private javax.swing.JComboBox jCBRoles;
    private javax.swing.JLabel jLabelAddress;
    private javax.swing.JLabel jLabelLocale;
    private javax.swing.JLabel jLabelMaxBuild;
    private javax.swing.JLabel jLabelMaxFailedAttempt;
    private javax.swing.JLabel jLabelMinBuild;
    private javax.swing.JLabel jLabelPort;
    private javax.swing.JLabel jLabelRole;
    private javax.swing.JLabel jLabelTimeout;
    private javax.swing.JLabel jLabelVersion;
    private javax.swing.JPanel jPanelLogin;
    private javax.swing.JPanel jPanelLoginParams;
    private javax.swing.JPanel jPanelServer;
    private javax.swing.JPanel jPanelServerControls;
    private javax.swing.JPanel jPanelServerParams;
    private javax.swing.JSpinner jSpinnerFailedAttempt;
    private javax.swing.JSpinner jSpinnerMaxBuild;
    private javax.swing.JSpinner jSpinnerMinBuild;
    private javax.swing.JSpinner jSpinnerPort;
    private javax.swing.JSpinner jSpinnerTimeout;
    private javax.swing.JTextField jTFAddress;
    private javax.swing.JTextField jTFVersion;
    private javax.swing.JTabbedPane jTabbedPane;
    // End of variables declaration//GEN-END:variables
}
