/*
 * Copyright 2016 Warkdev.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package eu.jangos.manager.gui.dialog;

import javax.swing.JOptionPane;

/**
 * DialogBan is the class handling extra-information for the ban action.
 * 
 * @author Warkdev
 * @version v1.0
 * @since 10-02-2016
 */
public class DialogBan extends javax.swing.JDialog {
       
    /**
     * Code is the EXIT code for this dialog.
     * JOptionPane.OK_OPTION if ok is clicked.
     * JOptionPane.CANCEL_OPTION if cancel is clicked.
     */
    private int code = JOptionPane.CANCEL_OPTION;
    
    /**
     * Creates new form DialogBan
     * @param parent
     * @param modal
     */
    public DialogBan(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();    
        this.setLocationRelativeTo(parent);
    }

    public int getDuration() {
        return (int) this.jSpinnerDuration.getValue();
    }

    public void setDuration(int duration) {
        this.jSpinnerDuration.setValue(duration);
    }

    public String getReason() {
        return (String) this.jTFReason.getText();
    }
    
    public void setReason(String reason) {
        this.jTFReason.setText(reason);
    }

    public int getCode() {
        return code;
    }

    public void setCode(int code) {
        this.code = code;
    }        
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jLabelReason = new javax.swing.JLabel();
        jTFReason = new javax.swing.JTextField();
        jLabelDuration = new javax.swing.JLabel();
        jSpinnerDuration = new javax.swing.JSpinner();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jButtonCancel = new javax.swing.JButton();
        jButtonOK = new javax.swing.JButton();

        setTitle("Please provide ban informations");
        setMaximumSize(new java.awt.Dimension(400, 150));
        setMinimumSize(new java.awt.Dimension(400, 150));
        setModalityType(java.awt.Dialog.ModalityType.APPLICATION_MODAL);
        setPreferredSize(new java.awt.Dimension(400, 150));
        setResizable(false);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabelReason.setText("Reason: ");
        jPanel1.add(jLabelReason, new java.awt.GridBagConstraints());

        jTFReason.setMaximumSize(new java.awt.Dimension(300, 25));
        jTFReason.setMinimumSize(new java.awt.Dimension(300, 25));
        jTFReason.setPreferredSize(new java.awt.Dimension(300, 25));
        jPanel1.add(jTFReason, new java.awt.GridBagConstraints());

        jLabelDuration.setText("Duration:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        jPanel1.add(jLabelDuration, gridBagConstraints);

        jSpinnerDuration.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1)));
        jSpinnerDuration.setMaximumSize(new java.awt.Dimension(80, 30));
        jSpinnerDuration.setMinimumSize(new java.awt.Dimension(80, 30));
        jSpinnerDuration.setPreferredSize(new java.awt.Dimension(80, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        jPanel1.add(jSpinnerDuration, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.insets = new java.awt.Insets(50, 0, 0, 0);
        jPanel1.add(jSeparator1, gridBagConstraints);

        jButtonCancel.setText("Cancel");
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonCancel);

        jButtonOK.setText("OK");
        jButtonOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOKActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonOK);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        jPanel1.add(jPanel2, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        getContentPane().add(jPanel1, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOKActionPerformed
        this.code = JOptionPane.OK_OPTION;
        this.dispose();
    }//GEN-LAST:event_jButtonOKActionPerformed

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        this.code = JOptionPane.CANCEL_OPTION;
        this.dispose();
    }//GEN-LAST:event_jButtonCancelActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonOK;
    private javax.swing.JLabel jLabelDuration;
    private javax.swing.JLabel jLabelReason;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSpinner jSpinnerDuration;
    private javax.swing.JTextField jTFReason;
    // End of variables declaration//GEN-END:variables
}
