/*
 * Copyright 2016 Warkdev.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package eu.jangos.manager.gui.dialog;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *  DialogLogin is the dialog opening at manager startup. It makes sure that the manager is authenticated.
 * 
 * @author Warkdev
 * @version 1.0
 * @since 13-02-2016
 */
public class DialogLogin extends javax.swing.JDialog {    
    
    /**
     * Code is the EXIT code for this dialog.
     * JOptionPane.OK_OPTION if ok is clicked.
     * JOptionPane.CANCEL_OPTION if cancel is clicked.
     */
    private int code = JOptionPane.CANCEL_OPTION;
    
    public DialogLogin() {
        super();
        initComponents();        
    }
    
    /**
     * Creates new form DialogLogin
     */
    public DialogLogin(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(parent);        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanelLogin = new javax.swing.JPanel();
        jLabelAccountName = new javax.swing.JLabel();
        jTFAccount = new javax.swing.JTextField();
        jLabelPassword = new javax.swing.JLabel();
        jPWpassword = new javax.swing.JPasswordField();
        jSeparator1 = new javax.swing.JSeparator();
        jPanelControls = new javax.swing.JPanel();
        jButtonCancel = new javax.swing.JButton();
        jButtonOK = new javax.swing.JButton();

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("eu/jangos/manager/Bundle"); // NOI18N
        setTitle(bundle.getString("DialogLogin.title")); // NOI18N
        setMaximumSize(new java.awt.Dimension(300, 150));
        setMinimumSize(new java.awt.Dimension(300, 150));
        setModal(true);
        setPreferredSize(new java.awt.Dimension(300, 150));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanelLogin.setLayout(new java.awt.GridBagLayout());

        jLabelAccountName.setText(bundle.getString("DialogLogin.jLabelAccountName.text")); // NOI18N
        jPanelLogin.add(jLabelAccountName, new java.awt.GridBagConstraints());

        jTFAccount.setMaximumSize(new java.awt.Dimension(110, 25));
        jTFAccount.setMinimumSize(new java.awt.Dimension(110, 25));
        jTFAccount.setPreferredSize(new java.awt.Dimension(110, 25));
        jTFAccount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTFAccountKeyReleased(evt);
            }
        });
        jPanelLogin.add(jTFAccount, new java.awt.GridBagConstraints());

        jLabelPassword.setText(bundle.getString("DialogLogin.jLabelPassword.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        jPanelLogin.add(jLabelPassword, gridBagConstraints);

        jPWpassword.setMaximumSize(new java.awt.Dimension(110, 25));
        jPWpassword.setMinimumSize(new java.awt.Dimension(110, 25));
        jPWpassword.setPreferredSize(new java.awt.Dimension(110, 25));
        jPWpassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jPWpasswordKeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        jPanelLogin.add(jPWpassword, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.insets = new java.awt.Insets(50, 0, 0, 0);
        jPanelLogin.add(jSeparator1, gridBagConstraints);

        jButtonCancel.setText(bundle.getString("DialogLogin.jButtonCancel.text")); // NOI18N
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });
        jPanelControls.add(jButtonCancel);

        jButtonOK.setText(bundle.getString("DialogLogin.jButtonOK.text")); // NOI18N
        jButtonOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOKActionPerformed(evt);
            }
        });
        jPanelControls.add(jButtonOK);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        jPanelLogin.add(jPanelControls, gridBagConstraints);

        getContentPane().add(jPanelLogin, new java.awt.GridBagConstraints());

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        this.code = JOptionPane.CANCEL_OPTION;
        this.dispose();
    }//GEN-LAST:event_jButtonCancelActionPerformed

    private void jButtonOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOKActionPerformed
        this.code = JOptionPane.OK_OPTION;
        this.dispose();
    }//GEN-LAST:event_jButtonOKActionPerformed

    private void jPWpasswordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPWpasswordKeyReleased
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
        {
            this.code = JOptionPane.OK_OPTION;
            this.dispose();
        }
    }//GEN-LAST:event_jPWpasswordKeyReleased

    private void jTFAccountKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFAccountKeyReleased
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
        {
            this.code = JOptionPane.OK_OPTION;
            this.dispose();
        }
    }//GEN-LAST:event_jTFAccountKeyReleased

    public int getCode() {
        return code;
    }

    public void setCode(int code) {
        this.code = code;
    }        

    /**
     * Return the entered password.
     * @return An array of chars containing the entered password.
     */
    public char[] getPassword() {
        return this.jPWpassword.getPassword();
    }
    
    /**
     * Return the entered account name.
     * @return A String containing the entered account name.
     */
    public String getName() {
        return this.jTFAccount.getText();
    }
    
    /**
     * Reset the graphical interface.
     */
    public void reset() {
        this.jPWpassword.setText("");
        this.jTFAccount.setText("");
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonOK;
    private javax.swing.JLabel jLabelAccountName;
    private javax.swing.JLabel jLabelPassword;
    private javax.swing.JPasswordField jPWpassword;
    private javax.swing.JPanel jPanelControls;
    private javax.swing.JPanel jPanelLogin;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTFAccount;
    // End of variables declaration//GEN-END:variables
}
